language: node_js
before_script:
  - npm install -g gatsby-cli
# node_js: EXECUTING TESTS RESULTED IN 'Error: no test specified' 
#  - "10"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: npm ci && yarn run deploy
  skip_cleanup: true
  on:
    branch: main
